#!/bin/sh

RED='\033[0;31m'
NC='\033[0m' # сброс цвета (No Color)

# Если это merge-коммит — пропускаем проверку
if grep -qE "^Merge " "$1"; then
  exit 0
fi

if ! head -1 "$1" | grep -qE "^(feat|fix|chore|docs|test|style|refactor|perf|build|ci|revert)(\(.+?\))?: .{1,}$"; then
    echo "${RED}Aborting commit. Your commit message is invalid." >&2
    exit 1
fi

if ! head -1 "$1" | grep -qE "^.{1,88}$"; then
    echo "${RED}Aborting commit. Your commit message is too long." >&2
    exit 1
fi